pidid: pidid.c
	cc pidid.c -o pidid
	
parentchild: parentchild.c
	cc parentchild.c -o parentchild

menu: menu.c
	cc menu.c -o menu

menushell: menushell.c
	cc menushell.c -o menushell 

helloworldfork: helloworldfork.c
	cc helloworldfork.c -o helloworldfork

sleepy: sleepy.c
	cc sleepy.c -o sleepy

sleepy2: sleepy2.c
	cc sleepy2.c -o sleepy2

doublefork: doublefork.c
	cc doublefork.c -o doublefork

myshell: myshell.c
	cc myshell.c -o myshell
	
waittest: waittest.c
	cc waittest.c -o waittest

globex: globex.c
	cc globex.c -o globex

shfile: shfile.c
	cc shfile.c -o shfile

lstest: lstest.c
	cc lstest.c -o lstest

clean:
	rm -f *.o pidid parentchild menu menushell hellowworldfork

