all: countvowels printascii printchar printfloat printfloats printstrings sumfifty swapint

countvowels: countvowels.c
		cc countvowels.c -o countvowels

printascii: printascii.c
		cc printascii.c -o printascii

printchar: printchar.c
		cc printchar.c -o printchar

printfloat: printfloat.c
		cc printfloat.c -o printfloat

printfloats: printfloats.c
		cc printfloats.c -o printfloats

printstrings: printstrings.c
		cc printstrings.c -o printstrings

sumfifty: sumfifty.c
		cc sumfifty.c -o sumfifty

swapint: swapint.c
		cc swapint.c -o swapint

clean:
		rm -f countvowels printascii printchar printfloat printfloats printstrings sumfifty swapint

