all: letters numbers firstname userinput newshell

letters: letters.c
	gcc letters.c -o letters

numbers: numbers.c
	gcc numbers.c -o numbers

firstname: firstname.c
	gcc firstname.c -o firstname

userinput: userinput.c
	gcc userinput.c -o userinput

newshell: newshell.c
	gcc newshell.c -o newshell

clean:
	rm -f *.o letters numbers firstname userinput newshell
